/**
 * Adobe Edge: symbol definitions
 */
(function($, Edge, compId){
//images folder
var im='images/';

var fonts = {};
var opts = {
    'gAudioPreloadPreference': 'auto',

    'gVideoPreloadPreference': 'auto'
};
var resources = [
];
var symbols = {
"stage": {
    version: "4.0.1",
    minimumCompatibleVersion: "4.0.1",
    build: "4.0.1.365",
    baseState: "Base State",
    scaleToFit: "width",
    centerStage: "none",
    initialState: "Base State",
    gpuAccelerate: false,
    resizeInstances: false,
    content: {
            dom: [
            {
                id: 'Rectangle5',
                type: 'rect',
                rect: ['481px', '137px','201px','178px','auto', 'auto'],
                fill: ["rgba(255,158,73,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'Rectangle',
                type: 'rect',
                rect: ['28px', '77px','92px','238px','auto', 'auto'],
                fill: ["rgba(255,73,73,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'Rectangle3',
                type: 'rect',
                rect: ['146px', '187px','379px','128px','auto', 'auto'],
                fill: ["rgba(249,73,255,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'Rectangle4',
                type: 'rect',
                rect: ['256px', '40px','126px','275px','auto', 'auto'],
                fill: ["rgba(0,185,11,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'Rectangle2',
                type: 'rect',
                rect: ['182px', '113px','110px','202px','auto', 'auto'],
                fill: ["rgba(73,78,255,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'Scan_line',
                type: 'rect',
                rect: ['0px', '0px','1px','315px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgba(0,0,0,1)","none"]
            },
            {
                id: 'segment1',
                display: 'none',
                type: 'rect',
                rect: ['28px', '74px','92px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy2',
                display: 'none',
                type: 'rect',
                rect: ['146px', '184px','36px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy8',
                display: 'none',
                type: 'rect',
                rect: ['256px', '184px','36px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy3',
                display: 'none',
                type: 'rect',
                rect: ['182px', '110px','74px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy7',
                display: 'none',
                type: 'rect',
                rect: ['182px', '184px','74px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy11',
                display: 'none',
                type: 'rect',
                rect: ['292px', '184px','90px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy4',
                display: 'none',
                type: 'rect',
                rect: ['256px', '37px','126px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy15',
                display: 'none',
                type: 'rect',
                rect: ['256px', '37px','126px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy5',
                display: 'none',
                type: 'rect',
                rect: ['382px', '184px','99px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy6',
                display: 'none',
                type: 'rect',
                rect: ['481px', '134px','201px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy16',
                display: 'none',
                type: 'rect',
                rect: ['525px', '134px','157px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy9',
                display: 'none',
                type: 'rect',
                rect: ['256px', '110px','36px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            },
            {
                id: 'segment1Copy10',
                display: 'none',
                type: 'rect',
                rect: ['481px', '184px','44px','3px','auto', 'auto'],
                fill: ["rgba(0,0,0,1.00)"],
                stroke: [0,"rgb(0, 0, 0)","solid"]
            }],
            symbolInstances: [

            ]
        },
    states: {
        "Base State": {
            "${_segment1}": [
                ["style", "top", '74px'],
                ["style", "height", '3px'],
                ["color", "background-color", 'rgba(0,0,0,1.00)'],
                ["style", "display", 'none'],
                ["style", "width", '92px']
            ],
            "${_Rectangle2}": [
                ["style", "top", '113px'],
                ["color", "background-color", 'rgba(73,78,255,1)'],
                ["style", "left", '182px'],
                ["style", "height", '202px'],
                ["style", "border-style", 'solid'],
                ["style", "border-width", '0px'],
                ["style", "width", '110px']
            ],
            "${_segment1Copy2}": [
                ["style", "top", '184px'],
                ["color", "background-color", 'rgba(0,0,0,1.00)'],
                ["style", "height", '3px'],
                ["style", "display", 'none'],
                ["style", "left", '146px'],
                ["style", "width", '36px']
            ],
            "${_segment1Copy9}": [
                ["style", "top", '110px'],
                ["color", "background-color", 'rgba(0,0,0,1)'],
                ["style", "height", '3px'],
                ["style", "display", 'none'],
                ["style", "left", '256px'],
                ["style", "width", '36px']
            ],
            "${_segment1Copy16}": [
                ["style", "top", '134px'],
                ["color", "background-color", 'rgba(0,0,0,1.00)'],
                ["style", "height", '3px'],
                ["style", "display", 'none'],
                ["style", "left", '525px'],
                ["style", "width", '157px']
            ],
            "${_segment1Copy8}": [
                ["style", "top", '184px'],
                ["color", "background-color", 'rgba(0,0,0,1)'],
                ["style", "height", '3px'],
                ["style", "display", 'none'],
                ["style", "left", '256px'],
                ["style", "width", '36px']
            ],
            "${_segment1Copy15}": [
                ["style", "top", '37px'],
                ["style", "display", 'none'],
                ["style", "height", '3px'],
                ["color", "background-color", 'rgba(0,0,0,1.00)'],
                ["style", "left", '292px'],
                ["style", "width", '90px']
            ],
            "${_segment1Copy5}": [
                ["style", "top", '184px'],
                ["color", "background-color", 'rgba(0,0,0,1.00)'],
                ["style", "height", '3px'],
                ["style", "display", 'none'],
                ["style", "left", '382px'],
                ["style", "width", '99px']
            ],
            "${_segment1Copy11}": [
                ["style", "top", '184px'],
                ["color", "background-color", 'rgba(0,0,0,1)'],
                ["style", "height", '3px'],
                ["style", "display", 'none'],
                ["style", "left", '292px'],
                ["style", "width", '90px']
            ],
            "${_Scan_line}": [
                ["style", "height", '315px'],
                ["color", "background-color", 'rgba(0,0,0,1.00)'],
                ["style", "left", '0px'],
                ["style", "width", '1px']
            ],
            "${_segment1Copy7}": [
                ["style", "top", '184px'],
                ["color", "background-color", 'rgba(0,0,0,1)'],
                ["style", "height", '3px'],
                ["style", "display", 'none'],
                ["style", "left", '182px'],
                ["style", "width", '74px']
            ],
            "${_Rectangle}": [
                ["color", "background-color", 'rgba(255,73,73,1)'],
                ["style", "top", '77px'],
                ["style", "height", '238px'],
                ["style", "border-style", 'solid'],
                ["style", "left", '28px'],
                ["style", "border-width", '0px']
            ],
            "${_Rectangle4}": [
                ["color", "background-color", 'rgba(0,185,11,1)'],
                ["style", "border-width", '0px'],
                ["style", "border-style", 'solid'],
                ["style", "left", '256px'],
                ["style", "top", '40px']
            ],
            "${_segment1Copy6}": [
                ["style", "top", '134px'],
                ["color", "background-color", 'rgba(0,0,0,1.00)'],
                ["style", "height", '3px'],
                ["style", "display", 'none'],
                ["style", "left", '481px'],
                ["style", "width", '44px']
            ],
            "${_Rectangle3}": [
                ["color", "background-color", 'rgba(249,73,255,1)'],
                ["style", "top", '187px'],
                ["style", "left", '146px'],
                ["style", "border-style", 'solid'],
                ["style", "border-width", '0px'],
                ["style", "width", '379px']
            ],
            "${_Stage}": [
                ["color", "background-color", 'rgba(255,255,255,0.00)'],
                ["style", "width", '703px'],
                ["style", "height", '315px'],
                ["style", "overflow", 'hidden']
            ],
            "${_Rectangle5}": [
                ["color", "background-color", 'rgba(255,158,73,1)'],
                ["style", "border-width", '0px'],
                ["style", "border-style", 'solid'],
                ["style", "left", '481px'],
                ["style", "top", '137px']
            ],
            "${_segment1Copy3}": [
                ["style", "top", '110px'],
                ["color", "background-color", 'rgba(0,0,0,1.00)'],
                ["style", "height", '3px'],
                ["style", "display", 'none'],
                ["style", "left", '182px'],
                ["style", "width", '74px']
            ],
            "${_segment1Copy10}": [
                ["style", "top", '184px'],
                ["color", "background-color", 'rgba(0,0,0,1)'],
                ["style", "height", '3px'],
                ["style", "display", 'none'],
                ["style", "left", '481px'],
                ["style", "width", '44px']
            ],
            "${_segment1Copy4}": [
                ["style", "top", '37px'],
                ["color", "background-color", 'rgba(0,0,0,1.00)'],
                ["style", "height", '3px'],
                ["style", "display", 'none'],
                ["style", "left", '256px'],
                ["style", "width", '36px']
            ]
        }
    },
    timelines: {
        "Default Timeline": {
            fromState: "Base State",
            toState: "",
            duration: 35100,
            autoPlay: true,
            timeline: [
                { id: "eid97", tween: [ "style", "${_Scan_line}", "left", '27px', { fromValue: '0px'}], position: 0, duration: 270 },
                { id: "eid223", tween: [ "style", "${_Scan_line}", "left", '119px', { fromValue: '27px'}], position: 2770, duration: 930 },
                { id: "eid274", tween: [ "style", "${_Scan_line}", "left", '146px', { fromValue: '119px'}], position: 6200, duration: 260 },
                { id: "eid366", tween: [ "style", "${_Scan_line}", "left", '181px', { fromValue: '146px'}], position: 8960, duration: 360 },
                { id: "eid400", tween: [ "style", "${_Scan_line}", "left", '255px', { fromValue: '181px'}], position: 11820, duration: 440 },
                { id: "eid438", tween: [ "style", "${_Scan_line}", "left", '291px', { fromValue: '255px'}], position: 14760, duration: 360 },
                { id: "eid481", tween: [ "style", "${_Scan_line}", "left", '381px', { fromValue: '291px'}], position: 17620, duration: 900 },
                { id: "eid514", tween: [ "style", "${_Scan_line}", "left", '480px', { fromValue: '381px'}], position: 21020, duration: 996 },
                { id: "eid550", tween: [ "style", "${_Scan_line}", "left", '525px', { fromValue: '480px'}], position: 24516, duration: 450 },
                { id: "eid587", tween: [ "style", "${_Scan_line}", "left", '702px', { fromValue: '525px'}], position: 27466, duration: 1770 },
                { id: "eid123", tween: [ "style", "${_segment1Copy11}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid476", tween: [ "style", "${_segment1Copy11}", "display", 'block', { fromValue: 'none'}], position: 15620, duration: 0 },
                { id: "eid477", tween: [ "style", "${_segment1Copy11}", "display", 'none', { fromValue: 'block'}], position: 16620, duration: 0 },
                { id: "eid119", tween: [ "style", "${_segment1Copy9}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid433", tween: [ "style", "${_segment1Copy9}", "display", 'block', { fromValue: 'none'}], position: 13260, duration: 0 },
                { id: "eid434", tween: [ "style", "${_segment1Copy9}", "display", 'none', { fromValue: 'block'}], position: 13760, duration: 0 },
                { id: "eid173", tween: [ "style", "${_Rectangle2}", "border-width", '0px', { fromValue: '0px'}], position: 0, duration: 0 },
                { id: "eid183", tween: [ "style", "${_Rectangle2}", "border-width", '3px', { fromValue: '0px'}], position: 1270, duration: 0 },
                { id: "eid188", tween: [ "style", "${_Rectangle2}", "border-width", '0px', { fromValue: '3px'}], position: 1770, duration: 0 },
                { id: "eid231", tween: [ "style", "${_Rectangle2}", "border-width", '3px', { fromValue: '0px'}], position: 4700, duration: 0 },
                { id: "eid232", tween: [ "style", "${_Rectangle2}", "border-width", '0px', { fromValue: '3px'}], position: 5200, duration: 0 },
                { id: "eid324", tween: [ "style", "${_Rectangle2}", "border-width", '3px', { fromValue: '0px'}], position: 7460, duration: 0 },
                { id: "eid325", tween: [ "style", "${_Rectangle2}", "border-width", '0px', { fromValue: '3px'}], position: 7960, duration: 0 },
                { id: "eid371", tween: [ "style", "${_Rectangle2}", "border-width", '3px', { fromValue: '0px'}], position: 10320, duration: 0 },
                { id: "eid372", tween: [ "style", "${_Rectangle2}", "border-width", '0px', { fromValue: '3px'}], position: 10820, duration: 0 },
                { id: "eid405", tween: [ "style", "${_Rectangle2}", "border-width", '3px', { fromValue: '0px'}], position: 13260, duration: 0 },
                { id: "eid406", tween: [ "style", "${_Rectangle2}", "border-width", '0px', { fromValue: '3px'}], position: 13760, duration: 0 },
                { id: "eid450", tween: [ "style", "${_Rectangle2}", "border-width", '3px', { fromValue: '0px'}], position: 16120, duration: 0 },
                { id: "eid451", tween: [ "style", "${_Rectangle2}", "border-width", '0px', { fromValue: '3px'}], position: 16620, duration: 0 },
                { id: "eid486", tween: [ "style", "${_Rectangle2}", "border-width", '3px', { fromValue: '0px'}], position: 19520, duration: 0 },
                { id: "eid487", tween: [ "style", "${_Rectangle2}", "border-width", '0px', { fromValue: '3px'}], position: 20020, duration: 0 },
                { id: "eid519", tween: [ "style", "${_Rectangle2}", "border-width", '3px', { fromValue: '0px'}], position: 23016, duration: 0 },
                { id: "eid520", tween: [ "style", "${_Rectangle2}", "border-width", '0px', { fromValue: '3px'}], position: 23516, duration: 0 },
                { id: "eid555", tween: [ "style", "${_Rectangle2}", "border-width", '3px', { fromValue: '0px'}], position: 25966, duration: 0 },
                { id: "eid556", tween: [ "style", "${_Rectangle2}", "border-width", '0px', { fromValue: '3px'}], position: 26466, duration: 0 },
                { id: "eid147", tween: [ "style", "${_Rectangle}", "top", '77px', { fromValue: '77px'}], position: 0, duration: 0 },
                { id: "eid153", tween: [ "style", "${_Rectangle}", "top", '74px', { fromValue: '77px'}], position: 270, duration: 0 },
                { id: "eid154", tween: [ "style", "${_Rectangle}", "top", '77px', { fromValue: '74px'}], position: 770, duration: 0 },
                { id: "eid252", tween: [ "style", "${_Rectangle}", "top", '74px', { fromValue: '77px'}], position: 3700, duration: 0 },
                { id: "eid253", tween: [ "style", "${_Rectangle}", "top", '77px', { fromValue: '74px'}], position: 4200, duration: 0 },
                { id: "eid345", tween: [ "style", "${_Rectangle}", "top", '74px', { fromValue: '77px'}], position: 6460, duration: 0 },
                { id: "eid346", tween: [ "style", "${_Rectangle}", "top", '77px', { fromValue: '74px'}], position: 6960, duration: 0 },
                { id: "eid385", tween: [ "style", "${_Rectangle}", "top", '74px', { fromValue: '77px'}], position: 9320, duration: 0 },
                { id: "eid386", tween: [ "style", "${_Rectangle}", "top", '77px', { fromValue: '74px'}], position: 9820, duration: 0 },
                { id: "eid419", tween: [ "style", "${_Rectangle}", "top", '74px', { fromValue: '77px'}], position: 12260, duration: 0 },
                { id: "eid420", tween: [ "style", "${_Rectangle}", "top", '77px', { fromValue: '74px'}], position: 12760, duration: 0 },
                { id: "eid464", tween: [ "style", "${_Rectangle}", "top", '74px', { fromValue: '77px'}], position: 15120, duration: 0 },
                { id: "eid465", tween: [ "style", "${_Rectangle}", "top", '77px', { fromValue: '74px'}], position: 15620, duration: 0 },
                { id: "eid500", tween: [ "style", "${_Rectangle}", "top", '74px', { fromValue: '77px'}], position: 18520, duration: 0 },
                { id: "eid501", tween: [ "style", "${_Rectangle}", "top", '77px', { fromValue: '74px'}], position: 19020, duration: 0 },
                { id: "eid533", tween: [ "style", "${_Rectangle}", "top", '74px', { fromValue: '77px'}], position: 22016, duration: 0 },
                { id: "eid534", tween: [ "style", "${_Rectangle}", "top", '77px', { fromValue: '74px'}], position: 22516, duration: 0 },
                { id: "eid569", tween: [ "style", "${_Rectangle}", "top", '74px', { fromValue: '77px'}], position: 24966, duration: 0 },
                { id: "eid570", tween: [ "style", "${_Rectangle}", "top", '77px', { fromValue: '74px'}], position: 25466, duration: 0 },
                { id: "eid121", tween: [ "style", "${_segment1Copy5}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid512", tween: [ "style", "${_segment1Copy5}", "display", 'block', { fromValue: 'none'}], position: 19020, duration: 0 },
                { id: "eid195", tween: [ "style", "${_Rectangle4}", "left", '256px', { fromValue: '256px'}], position: 0, duration: 0 },
                { id: "eid201", tween: [ "style", "${_Rectangle4}", "left", '253px', { fromValue: '256px'}], position: 1770, duration: 0 },
                { id: "eid202", tween: [ "style", "${_Rectangle4}", "left", '256px', { fromValue: '253px'}], position: 2270, duration: 0 },
                { id: "eid237", tween: [ "style", "${_Rectangle4}", "left", '253px', { fromValue: '256px'}], position: 5200, duration: 0 },
                { id: "eid238", tween: [ "style", "${_Rectangle4}", "left", '256px', { fromValue: '253px'}], position: 5700, duration: 0 },
                { id: "eid330", tween: [ "style", "${_Rectangle4}", "left", '253px', { fromValue: '256px'}], position: 7960, duration: 0 },
                { id: "eid331", tween: [ "style", "${_Rectangle4}", "left", '256px', { fromValue: '253px'}], position: 8460, duration: 0 },
                { id: "eid375", tween: [ "style", "${_Rectangle4}", "left", '253px', { fromValue: '256px'}], position: 10820, duration: 0 },
                { id: "eid376", tween: [ "style", "${_Rectangle4}", "left", '256px', { fromValue: '253px'}], position: 11320, duration: 0 },
                { id: "eid409", tween: [ "style", "${_Rectangle4}", "left", '253px', { fromValue: '256px'}], position: 13760, duration: 0 },
                { id: "eid410", tween: [ "style", "${_Rectangle4}", "left", '256px', { fromValue: '253px'}], position: 14260, duration: 0 },
                { id: "eid454", tween: [ "style", "${_Rectangle4}", "left", '253px', { fromValue: '256px'}], position: 16620, duration: 0 },
                { id: "eid455", tween: [ "style", "${_Rectangle4}", "left", '256px', { fromValue: '253px'}], position: 17120, duration: 0 },
                { id: "eid490", tween: [ "style", "${_Rectangle4}", "left", '253px', { fromValue: '256px'}], position: 20020, duration: 0 },
                { id: "eid491", tween: [ "style", "${_Rectangle4}", "left", '256px', { fromValue: '253px'}], position: 20520, duration: 0 },
                { id: "eid523", tween: [ "style", "${_Rectangle4}", "left", '253px', { fromValue: '256px'}], position: 23516, duration: 0 },
                { id: "eid524", tween: [ "style", "${_Rectangle4}", "left", '256px', { fromValue: '253px'}], position: 24016, duration: 0 },
                { id: "eid559", tween: [ "style", "${_Rectangle4}", "left", '253px', { fromValue: '256px'}], position: 26466, duration: 0 },
                { id: "eid560", tween: [ "style", "${_Rectangle4}", "left", '256px', { fromValue: '253px'}], position: 26966, duration: 0 },
                { id: "eid163", tween: [ "style", "${_Rectangle3}", "left", '146px', { fromValue: '146px'}], position: 0, duration: 0 },
                { id: "eid169", tween: [ "style", "${_Rectangle3}", "left", '143px', { fromValue: '146px'}], position: 770, duration: 0 },
                { id: "eid170", tween: [ "style", "${_Rectangle3}", "left", '146px', { fromValue: '143px'}], position: 1270, duration: 0 },
                { id: "eid246", tween: [ "style", "${_Rectangle3}", "left", '143px', { fromValue: '146px'}], position: 4200, duration: 0 },
                { id: "eid247", tween: [ "style", "${_Rectangle3}", "left", '146px', { fromValue: '143px'}], position: 4700, duration: 0 },
                { id: "eid339", tween: [ "style", "${_Rectangle3}", "left", '143px', { fromValue: '146px'}], position: 6960, duration: 0 },
                { id: "eid340", tween: [ "style", "${_Rectangle3}", "left", '146px', { fromValue: '143px'}], position: 7460, duration: 0 },
                { id: "eid381", tween: [ "style", "${_Rectangle3}", "left", '143px', { fromValue: '146px'}], position: 9820, duration: 0 },
                { id: "eid382", tween: [ "style", "${_Rectangle3}", "left", '146px', { fromValue: '143px'}], position: 10320, duration: 0 },
                { id: "eid415", tween: [ "style", "${_Rectangle3}", "left", '143px', { fromValue: '146px'}], position: 12760, duration: 0 },
                { id: "eid416", tween: [ "style", "${_Rectangle3}", "left", '146px', { fromValue: '143px'}], position: 13260, duration: 0 },
                { id: "eid460", tween: [ "style", "${_Rectangle3}", "left", '143px', { fromValue: '146px'}], position: 15620, duration: 0 },
                { id: "eid461", tween: [ "style", "${_Rectangle3}", "left", '146px', { fromValue: '143px'}], position: 16120, duration: 0 },
                { id: "eid496", tween: [ "style", "${_Rectangle3}", "left", '143px', { fromValue: '146px'}], position: 19020, duration: 0 },
                { id: "eid497", tween: [ "style", "${_Rectangle3}", "left", '146px', { fromValue: '143px'}], position: 19520, duration: 0 },
                { id: "eid529", tween: [ "style", "${_Rectangle3}", "left", '143px', { fromValue: '146px'}], position: 22516, duration: 0 },
                { id: "eid530", tween: [ "style", "${_Rectangle3}", "left", '146px', { fromValue: '143px'}], position: 23016, duration: 0 },
                { id: "eid565", tween: [ "style", "${_Rectangle3}", "left", '143px', { fromValue: '146px'}], position: 25466, duration: 0 },
                { id: "eid566", tween: [ "style", "${_Rectangle3}", "left", '146px', { fromValue: '143px'}], position: 25966, duration: 0 },
                { id: "eid127", tween: [ "style", "${_segment1Copy2}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid364", tween: [ "style", "${_segment1Copy2}", "display", 'block', { fromValue: 'none'}], position: 6960, duration: 0 },
                { id: "eid146", tween: [ "style", "${_Rectangle}", "left", '28px', { fromValue: '28px'}], position: 0, duration: 0 },
                { id: "eid152", tween: [ "style", "${_Rectangle}", "left", '25px', { fromValue: '28px'}], position: 270, duration: 0 },
                { id: "eid156", tween: [ "style", "${_Rectangle}", "left", '28px', { fromValue: '25px'}], position: 770, duration: 0 },
                { id: "eid255", tween: [ "style", "${_Rectangle}", "left", '25px', { fromValue: '28px'}], position: 3700, duration: 0 },
                { id: "eid256", tween: [ "style", "${_Rectangle}", "left", '28px', { fromValue: '25px'}], position: 4200, duration: 0 },
                { id: "eid348", tween: [ "style", "${_Rectangle}", "left", '25px', { fromValue: '28px'}], position: 6460, duration: 0 },
                { id: "eid349", tween: [ "style", "${_Rectangle}", "left", '28px', { fromValue: '25px'}], position: 6960, duration: 0 },
                { id: "eid387", tween: [ "style", "${_Rectangle}", "left", '25px', { fromValue: '28px'}], position: 9320, duration: 0 },
                { id: "eid388", tween: [ "style", "${_Rectangle}", "left", '28px', { fromValue: '25px'}], position: 9820, duration: 0 },
                { id: "eid421", tween: [ "style", "${_Rectangle}", "left", '25px', { fromValue: '28px'}], position: 12260, duration: 0 },
                { id: "eid422", tween: [ "style", "${_Rectangle}", "left", '28px', { fromValue: '25px'}], position: 12760, duration: 0 },
                { id: "eid466", tween: [ "style", "${_Rectangle}", "left", '25px', { fromValue: '28px'}], position: 15120, duration: 0 },
                { id: "eid467", tween: [ "style", "${_Rectangle}", "left", '28px', { fromValue: '25px'}], position: 15620, duration: 0 },
                { id: "eid502", tween: [ "style", "${_Rectangle}", "left", '25px', { fromValue: '28px'}], position: 18520, duration: 0 },
                { id: "eid503", tween: [ "style", "${_Rectangle}", "left", '28px', { fromValue: '25px'}], position: 19020, duration: 0 },
                { id: "eid535", tween: [ "style", "${_Rectangle}", "left", '25px', { fromValue: '28px'}], position: 22016, duration: 0 },
                { id: "eid536", tween: [ "style", "${_Rectangle}", "left", '28px', { fromValue: '25px'}], position: 22516, duration: 0 },
                { id: "eid571", tween: [ "style", "${_Rectangle}", "left", '25px', { fromValue: '28px'}], position: 24966, duration: 0 },
                { id: "eid572", tween: [ "style", "${_Rectangle}", "left", '28px', { fromValue: '25px'}], position: 25466, duration: 0 },
                { id: "eid120", tween: [ "style", "${_segment1Copy6}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid548", tween: [ "style", "${_segment1Copy6}", "display", 'block', { fromValue: 'none'}], position: 24016, duration: 0 },
                { id: "eid118", tween: [ "style", "${_segment1Copy10}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid545", tween: [ "style", "${_segment1Copy10}", "display", 'block', { fromValue: 'none'}], position: 22516, duration: 0 },
                { id: "eid546", tween: [ "style", "${_segment1Copy10}", "display", 'none', { fromValue: 'block'}], position: 24016, duration: 0 },
                { id: "eid117", tween: [ "style", "${_segment1}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid150", tween: [ "style", "${_segment1}", "display", 'block', { fromValue: 'none'}], position: 270, duration: 0 },
                { id: "eid164", tween: [ "style", "${_Rectangle3}", "top", '187px', { fromValue: '187px'}], position: 0, duration: 0 },
                { id: "eid168", tween: [ "style", "${_Rectangle3}", "top", '184px', { fromValue: '187px'}], position: 770, duration: 0 },
                { id: "eid171", tween: [ "style", "${_Rectangle3}", "top", '187px', { fromValue: '184px'}], position: 1270, duration: 0 },
                { id: "eid243", tween: [ "style", "${_Rectangle3}", "top", '184px', { fromValue: '187px'}], position: 4200, duration: 0 },
                { id: "eid244", tween: [ "style", "${_Rectangle3}", "top", '187px', { fromValue: '184px'}], position: 4700, duration: 0 },
                { id: "eid336", tween: [ "style", "${_Rectangle3}", "top", '184px', { fromValue: '187px'}], position: 6960, duration: 0 },
                { id: "eid337", tween: [ "style", "${_Rectangle3}", "top", '187px', { fromValue: '184px'}], position: 7460, duration: 0 },
                { id: "eid379", tween: [ "style", "${_Rectangle3}", "top", '184px', { fromValue: '187px'}], position: 9820, duration: 0 },
                { id: "eid380", tween: [ "style", "${_Rectangle3}", "top", '187px', { fromValue: '184px'}], position: 10320, duration: 0 },
                { id: "eid413", tween: [ "style", "${_Rectangle3}", "top", '184px', { fromValue: '187px'}], position: 12760, duration: 0 },
                { id: "eid414", tween: [ "style", "${_Rectangle3}", "top", '187px', { fromValue: '184px'}], position: 13260, duration: 0 },
                { id: "eid458", tween: [ "style", "${_Rectangle3}", "top", '184px', { fromValue: '187px'}], position: 15620, duration: 0 },
                { id: "eid459", tween: [ "style", "${_Rectangle3}", "top", '187px', { fromValue: '184px'}], position: 16120, duration: 0 },
                { id: "eid494", tween: [ "style", "${_Rectangle3}", "top", '184px', { fromValue: '187px'}], position: 19020, duration: 0 },
                { id: "eid495", tween: [ "style", "${_Rectangle3}", "top", '187px', { fromValue: '184px'}], position: 19520, duration: 0 },
                { id: "eid527", tween: [ "style", "${_Rectangle3}", "top", '184px', { fromValue: '187px'}], position: 22516, duration: 0 },
                { id: "eid528", tween: [ "style", "${_Rectangle3}", "top", '187px', { fromValue: '184px'}], position: 23016, duration: 0 },
                { id: "eid563", tween: [ "style", "${_Rectangle3}", "top", '184px', { fromValue: '187px'}], position: 25466, duration: 0 },
                { id: "eid564", tween: [ "style", "${_Rectangle3}", "top", '187px', { fromValue: '184px'}], position: 25966, duration: 0 },
                { id: "eid122", tween: [ "style", "${_segment1Copy4}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid436", tween: [ "style", "${_segment1Copy4}", "display", 'block', { fromValue: 'none'}], position: 13760, duration: 0 },
                { id: "eid124", tween: [ "style", "${_segment1Copy7}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid137", tween: [ "style", "${_segment1Copy7}", "display", 'block', { fromValue: 'none'}], position: 9820, duration: 0 },
                { id: "eid397", tween: [ "style", "${_segment1Copy7}", "display", 'none', { fromValue: 'block'}], position: 10320, duration: 0 },
                { id: "eid126", tween: [ "style", "${_segment1Copy8}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid431", tween: [ "style", "${_segment1Copy8}", "display", 'block', { fromValue: 'none'}], position: 12760, duration: 0 },
                { id: "eid432", tween: [ "style", "${_segment1Copy8}", "display", 'none', { fromValue: 'block'}], position: 13260, duration: 0 },
                { id: "eid178", tween: [ "style", "${_Rectangle2}", "left", '182px', { fromValue: '182px'}], position: 0, duration: 0 },
                { id: "eid184", tween: [ "style", "${_Rectangle2}", "left", '179px', { fromValue: '182px'}], position: 1270, duration: 0 },
                { id: "eid186", tween: [ "style", "${_Rectangle2}", "left", '182px', { fromValue: '179px'}], position: 1770, duration: 0 },
                { id: "eid228", tween: [ "style", "${_Rectangle2}", "left", '179px', { fromValue: '182px'}], position: 4700, duration: 0 },
                { id: "eid229", tween: [ "style", "${_Rectangle2}", "left", '182px', { fromValue: '179px'}], position: 5200, duration: 0 },
                { id: "eid321", tween: [ "style", "${_Rectangle2}", "left", '179px', { fromValue: '182px'}], position: 7460, duration: 0 },
                { id: "eid322", tween: [ "style", "${_Rectangle2}", "left", '182px', { fromValue: '179px'}], position: 7960, duration: 0 },
                { id: "eid369", tween: [ "style", "${_Rectangle2}", "left", '179px', { fromValue: '182px'}], position: 10320, duration: 0 },
                { id: "eid370", tween: [ "style", "${_Rectangle2}", "left", '182px', { fromValue: '179px'}], position: 10820, duration: 0 },
                { id: "eid403", tween: [ "style", "${_Rectangle2}", "left", '179px', { fromValue: '182px'}], position: 13260, duration: 0 },
                { id: "eid404", tween: [ "style", "${_Rectangle2}", "left", '182px', { fromValue: '179px'}], position: 13760, duration: 0 },
                { id: "eid448", tween: [ "style", "${_Rectangle2}", "left", '179px', { fromValue: '182px'}], position: 16120, duration: 0 },
                { id: "eid449", tween: [ "style", "${_Rectangle2}", "left", '182px', { fromValue: '179px'}], position: 16620, duration: 0 },
                { id: "eid484", tween: [ "style", "${_Rectangle2}", "left", '179px', { fromValue: '182px'}], position: 19520, duration: 0 },
                { id: "eid485", tween: [ "style", "${_Rectangle2}", "left", '182px', { fromValue: '179px'}], position: 20020, duration: 0 },
                { id: "eid517", tween: [ "style", "${_Rectangle2}", "left", '179px', { fromValue: '182px'}], position: 23016, duration: 0 },
                { id: "eid518", tween: [ "style", "${_Rectangle2}", "left", '182px', { fromValue: '179px'}], position: 23516, duration: 0 },
                { id: "eid553", tween: [ "style", "${_Rectangle2}", "left", '179px', { fromValue: '182px'}], position: 25966, duration: 0 },
                { id: "eid554", tween: [ "style", "${_Rectangle2}", "left", '182px', { fromValue: '179px'}], position: 26466, duration: 0 },
                { id: "eid196", tween: [ "style", "${_Rectangle4}", "top", '40px', { fromValue: '40px'}], position: 0, duration: 0 },
                { id: "eid200", tween: [ "style", "${_Rectangle4}", "top", '37px', { fromValue: '40px'}], position: 1770, duration: 0 },
                { id: "eid203", tween: [ "style", "${_Rectangle4}", "top", '40px', { fromValue: '37px'}], position: 2270, duration: 0 },
                { id: "eid234", tween: [ "style", "${_Rectangle4}", "top", '37px', { fromValue: '40px'}], position: 5200, duration: 0 },
                { id: "eid235", tween: [ "style", "${_Rectangle4}", "top", '40px', { fromValue: '37px'}], position: 5700, duration: 0 },
                { id: "eid327", tween: [ "style", "${_Rectangle4}", "top", '37px', { fromValue: '40px'}], position: 7960, duration: 0 },
                { id: "eid328", tween: [ "style", "${_Rectangle4}", "top", '40px', { fromValue: '37px'}], position: 8460, duration: 0 },
                { id: "eid373", tween: [ "style", "${_Rectangle4}", "top", '37px', { fromValue: '40px'}], position: 10820, duration: 0 },
                { id: "eid374", tween: [ "style", "${_Rectangle4}", "top", '40px', { fromValue: '37px'}], position: 11320, duration: 0 },
                { id: "eid407", tween: [ "style", "${_Rectangle4}", "top", '37px', { fromValue: '40px'}], position: 13760, duration: 0 },
                { id: "eid408", tween: [ "style", "${_Rectangle4}", "top", '40px', { fromValue: '37px'}], position: 14260, duration: 0 },
                { id: "eid452", tween: [ "style", "${_Rectangle4}", "top", '37px', { fromValue: '40px'}], position: 16620, duration: 0 },
                { id: "eid453", tween: [ "style", "${_Rectangle4}", "top", '40px', { fromValue: '37px'}], position: 17120, duration: 0 },
                { id: "eid488", tween: [ "style", "${_Rectangle4}", "top", '37px', { fromValue: '40px'}], position: 20020, duration: 0 },
                { id: "eid489", tween: [ "style", "${_Rectangle4}", "top", '40px', { fromValue: '37px'}], position: 20520, duration: 0 },
                { id: "eid521", tween: [ "style", "${_Rectangle4}", "top", '37px', { fromValue: '40px'}], position: 23516, duration: 0 },
                { id: "eid522", tween: [ "style", "${_Rectangle4}", "top", '40px', { fromValue: '37px'}], position: 24016, duration: 0 },
                { id: "eid557", tween: [ "style", "${_Rectangle4}", "top", '37px', { fromValue: '40px'}], position: 26466, duration: 0 },
                { id: "eid558", tween: [ "style", "${_Rectangle4}", "top", '40px', { fromValue: '37px'}], position: 26966, duration: 0 },
                { id: "eid584", tween: [ "style", "${_segment1Copy16}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid585", tween: [ "style", "${_segment1Copy16}", "display", 'block', { fromValue: 'none'}], position: 26966, duration: 0 },
                { id: "eid179", tween: [ "style", "${_Rectangle2}", "top", '113px', { fromValue: '113px'}], position: 0, duration: 0 },
                { id: "eid185", tween: [ "style", "${_Rectangle2}", "top", '110px', { fromValue: '113px'}], position: 1270, duration: 0 },
                { id: "eid187", tween: [ "style", "${_Rectangle2}", "top", '113px', { fromValue: '110px'}], position: 1770, duration: 0 },
                { id: "eid225", tween: [ "style", "${_Rectangle2}", "top", '110px', { fromValue: '113px'}], position: 4700, duration: 0 },
                { id: "eid226", tween: [ "style", "${_Rectangle2}", "top", '113px', { fromValue: '110px'}], position: 5200, duration: 0 },
                { id: "eid318", tween: [ "style", "${_Rectangle2}", "top", '110px', { fromValue: '113px'}], position: 7460, duration: 0 },
                { id: "eid319", tween: [ "style", "${_Rectangle2}", "top", '113px', { fromValue: '110px'}], position: 7960, duration: 0 },
                { id: "eid367", tween: [ "style", "${_Rectangle2}", "top", '110px', { fromValue: '113px'}], position: 10320, duration: 0 },
                { id: "eid368", tween: [ "style", "${_Rectangle2}", "top", '113px', { fromValue: '110px'}], position: 10820, duration: 0 },
                { id: "eid401", tween: [ "style", "${_Rectangle2}", "top", '110px', { fromValue: '113px'}], position: 13260, duration: 0 },
                { id: "eid402", tween: [ "style", "${_Rectangle2}", "top", '113px', { fromValue: '110px'}], position: 13760, duration: 0 },
                { id: "eid446", tween: [ "style", "${_Rectangle2}", "top", '110px', { fromValue: '113px'}], position: 16120, duration: 0 },
                { id: "eid447", tween: [ "style", "${_Rectangle2}", "top", '113px', { fromValue: '110px'}], position: 16620, duration: 0 },
                { id: "eid482", tween: [ "style", "${_Rectangle2}", "top", '110px', { fromValue: '113px'}], position: 19520, duration: 0 },
                { id: "eid483", tween: [ "style", "${_Rectangle2}", "top", '113px', { fromValue: '110px'}], position: 20020, duration: 0 },
                { id: "eid515", tween: [ "style", "${_Rectangle2}", "top", '110px', { fromValue: '113px'}], position: 23016, duration: 0 },
                { id: "eid516", tween: [ "style", "${_Rectangle2}", "top", '113px', { fromValue: '110px'}], position: 23516, duration: 0 },
                { id: "eid551", tween: [ "style", "${_Rectangle2}", "top", '110px', { fromValue: '113px'}], position: 25966, duration: 0 },
                { id: "eid552", tween: [ "style", "${_Rectangle2}", "top", '113px', { fromValue: '110px'}], position: 26466, duration: 0 },
                { id: "eid211", tween: [ "style", "${_Rectangle5}", "left", '481px', { fromValue: '481px'}], position: 0, duration: 0 },
                { id: "eid218", tween: [ "style", "${_Rectangle5}", "left", '478px', { fromValue: '481px'}], position: 2270, duration: 0 },
                { id: "eid220", tween: [ "style", "${_Rectangle5}", "left", '481px', { fromValue: '478px'}], position: 2770, duration: 0 },
                { id: "eid264", tween: [ "style", "${_Rectangle5}", "left", '478px', { fromValue: '481px'}], position: 5700, duration: 0 },
                { id: "eid265", tween: [ "style", "${_Rectangle5}", "left", '481px', { fromValue: '478px'}], position: 6200, duration: 0 },
                { id: "eid357", tween: [ "style", "${_Rectangle5}", "left", '478px', { fromValue: '481px'}], position: 8460, duration: 0 },
                { id: "eid358", tween: [ "style", "${_Rectangle5}", "left", '481px', { fromValue: '478px'}], position: 8960, duration: 0 },
                { id: "eid393", tween: [ "style", "${_Rectangle5}", "left", '478px', { fromValue: '481px'}], position: 11320, duration: 0 },
                { id: "eid394", tween: [ "style", "${_Rectangle5}", "left", '481px', { fromValue: '478px'}], position: 11820, duration: 0 },
                { id: "eid427", tween: [ "style", "${_Rectangle5}", "left", '478px', { fromValue: '481px'}], position: 14260, duration: 0 },
                { id: "eid428", tween: [ "style", "${_Rectangle5}", "left", '481px', { fromValue: '478px'}], position: 14760, duration: 0 },
                { id: "eid472", tween: [ "style", "${_Rectangle5}", "left", '478px', { fromValue: '481px'}], position: 17120, duration: 0 },
                { id: "eid473", tween: [ "style", "${_Rectangle5}", "left", '481px', { fromValue: '478px'}], position: 17620, duration: 0 },
                { id: "eid508", tween: [ "style", "${_Rectangle5}", "left", '478px', { fromValue: '481px'}], position: 20520, duration: 0 },
                { id: "eid509", tween: [ "style", "${_Rectangle5}", "left", '481px', { fromValue: '478px'}], position: 21020, duration: 0 },
                { id: "eid541", tween: [ "style", "${_Rectangle5}", "left", '478px', { fromValue: '481px'}], position: 24016, duration: 0 },
                { id: "eid542", tween: [ "style", "${_Rectangle5}", "left", '481px', { fromValue: '478px'}], position: 24516, duration: 0 },
                { id: "eid577", tween: [ "style", "${_Rectangle5}", "left", '478px', { fromValue: '481px'}], position: 26966, duration: 0 },
                { id: "eid578", tween: [ "style", "${_Rectangle5}", "left", '481px', { fromValue: '478px'}], position: 27466, duration: 0 },
                { id: "eid101", tween: [ "style", "${_Rectangle}", "border-width", '0px', { fromValue: '0px'}], position: 0, duration: 0 },
                { id: "eid151", tween: [ "style", "${_Rectangle}", "border-width", '3px', { fromValue: '0px'}], position: 270, duration: 0 },
                { id: "eid155", tween: [ "style", "${_Rectangle}", "border-width", '0px', { fromValue: '3px'}], position: 770, duration: 0 },
                { id: "eid258", tween: [ "style", "${_Rectangle}", "border-width", '3px', { fromValue: '0px'}], position: 3700, duration: 0 },
                { id: "eid259", tween: [ "style", "${_Rectangle}", "border-width", '0px', { fromValue: '3px'}], position: 4200, duration: 0 },
                { id: "eid351", tween: [ "style", "${_Rectangle}", "border-width", '3px', { fromValue: '0px'}], position: 6460, duration: 0 },
                { id: "eid352", tween: [ "style", "${_Rectangle}", "border-width", '0px', { fromValue: '3px'}], position: 6960, duration: 0 },
                { id: "eid389", tween: [ "style", "${_Rectangle}", "border-width", '3px', { fromValue: '0px'}], position: 9320, duration: 0 },
                { id: "eid390", tween: [ "style", "${_Rectangle}", "border-width", '0px', { fromValue: '3px'}], position: 9820, duration: 0 },
                { id: "eid423", tween: [ "style", "${_Rectangle}", "border-width", '3px', { fromValue: '0px'}], position: 12260, duration: 0 },
                { id: "eid424", tween: [ "style", "${_Rectangle}", "border-width", '0px', { fromValue: '3px'}], position: 12760, duration: 0 },
                { id: "eid468", tween: [ "style", "${_Rectangle}", "border-width", '3px', { fromValue: '0px'}], position: 15120, duration: 0 },
                { id: "eid469", tween: [ "style", "${_Rectangle}", "border-width", '0px', { fromValue: '3px'}], position: 15620, duration: 0 },
                { id: "eid504", tween: [ "style", "${_Rectangle}", "border-width", '3px', { fromValue: '0px'}], position: 18520, duration: 0 },
                { id: "eid505", tween: [ "style", "${_Rectangle}", "border-width", '0px', { fromValue: '3px'}], position: 19020, duration: 0 },
                { id: "eid537", tween: [ "style", "${_Rectangle}", "border-width", '3px', { fromValue: '0px'}], position: 22016, duration: 0 },
                { id: "eid538", tween: [ "style", "${_Rectangle}", "border-width", '0px', { fromValue: '3px'}], position: 22516, duration: 0 },
                { id: "eid573", tween: [ "style", "${_Rectangle}", "border-width", '3px', { fromValue: '0px'}], position: 24966, duration: 0 },
                { id: "eid574", tween: [ "style", "${_Rectangle}", "border-width", '0px', { fromValue: '3px'}], position: 25466, duration: 0 },
                { id: "eid212", tween: [ "style", "${_Rectangle5}", "top", '137px', { fromValue: '137px'}], position: 0, duration: 0 },
                { id: "eid219", tween: [ "style", "${_Rectangle5}", "top", '134px', { fromValue: '137px'}], position: 2270, duration: 0 },
                { id: "eid221", tween: [ "style", "${_Rectangle5}", "top", '137px', { fromValue: '134px'}], position: 2770, duration: 0 },
                { id: "eid261", tween: [ "style", "${_Rectangle5}", "top", '134px', { fromValue: '137px'}], position: 5700, duration: 0 },
                { id: "eid262", tween: [ "style", "${_Rectangle5}", "top", '137px', { fromValue: '134px'}], position: 6200, duration: 0 },
                { id: "eid354", tween: [ "style", "${_Rectangle5}", "top", '134px', { fromValue: '137px'}], position: 8460, duration: 0 },
                { id: "eid355", tween: [ "style", "${_Rectangle5}", "top", '137px', { fromValue: '134px'}], position: 8960, duration: 0 },
                { id: "eid391", tween: [ "style", "${_Rectangle5}", "top", '134px', { fromValue: '137px'}], position: 11320, duration: 0 },
                { id: "eid392", tween: [ "style", "${_Rectangle5}", "top", '137px', { fromValue: '134px'}], position: 11820, duration: 0 },
                { id: "eid425", tween: [ "style", "${_Rectangle5}", "top", '134px', { fromValue: '137px'}], position: 14260, duration: 0 },
                { id: "eid426", tween: [ "style", "${_Rectangle5}", "top", '137px', { fromValue: '134px'}], position: 14760, duration: 0 },
                { id: "eid470", tween: [ "style", "${_Rectangle5}", "top", '134px', { fromValue: '137px'}], position: 17120, duration: 0 },
                { id: "eid471", tween: [ "style", "${_Rectangle5}", "top", '137px', { fromValue: '134px'}], position: 17620, duration: 0 },
                { id: "eid506", tween: [ "style", "${_Rectangle5}", "top", '134px', { fromValue: '137px'}], position: 20520, duration: 0 },
                { id: "eid507", tween: [ "style", "${_Rectangle5}", "top", '137px', { fromValue: '134px'}], position: 21020, duration: 0 },
                { id: "eid539", tween: [ "style", "${_Rectangle5}", "top", '134px', { fromValue: '137px'}], position: 24016, duration: 0 },
                { id: "eid540", tween: [ "style", "${_Rectangle5}", "top", '137px', { fromValue: '134px'}], position: 24516, duration: 0 },
                { id: "eid575", tween: [ "style", "${_Rectangle5}", "top", '134px', { fromValue: '137px'}], position: 26966, duration: 0 },
                { id: "eid576", tween: [ "style", "${_Rectangle5}", "top", '137px', { fromValue: '134px'}], position: 27466, duration: 0 },
                { id: "eid445", tween: [ "style", "${_segment1Copy15}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid479", tween: [ "style", "${_segment1Copy15}", "display", 'block', { fromValue: 'none'}], position: 16620, duration: 0 },
                { id: "eid157", tween: [ "style", "${_Rectangle3}", "border-width", '0px', { fromValue: '0px'}], position: 0, duration: 0 },
                { id: "eid167", tween: [ "style", "${_Rectangle3}", "border-width", '3px', { fromValue: '0px'}], position: 770, duration: 0 },
                { id: "eid172", tween: [ "style", "${_Rectangle3}", "border-width", '0px', { fromValue: '3px'}], position: 1270, duration: 0 },
                { id: "eid249", tween: [ "style", "${_Rectangle3}", "border-width", '3px', { fromValue: '0px'}], position: 4200, duration: 0 },
                { id: "eid250", tween: [ "style", "${_Rectangle3}", "border-width", '0px', { fromValue: '3px'}], position: 4700, duration: 0 },
                { id: "eid342", tween: [ "style", "${_Rectangle3}", "border-width", '3px', { fromValue: '0px'}], position: 6960, duration: 0 },
                { id: "eid343", tween: [ "style", "${_Rectangle3}", "border-width", '0px', { fromValue: '3px'}], position: 7460, duration: 0 },
                { id: "eid383", tween: [ "style", "${_Rectangle3}", "border-width", '3px', { fromValue: '0px'}], position: 9820, duration: 0 },
                { id: "eid384", tween: [ "style", "${_Rectangle3}", "border-width", '0px', { fromValue: '3px'}], position: 10320, duration: 0 },
                { id: "eid417", tween: [ "style", "${_Rectangle3}", "border-width", '3px', { fromValue: '0px'}], position: 12760, duration: 0 },
                { id: "eid418", tween: [ "style", "${_Rectangle3}", "border-width", '0px', { fromValue: '3px'}], position: 13260, duration: 0 },
                { id: "eid462", tween: [ "style", "${_Rectangle3}", "border-width", '3px', { fromValue: '0px'}], position: 15620, duration: 0 },
                { id: "eid463", tween: [ "style", "${_Rectangle3}", "border-width", '0px', { fromValue: '3px'}], position: 16120, duration: 0 },
                { id: "eid498", tween: [ "style", "${_Rectangle3}", "border-width", '3px', { fromValue: '0px'}], position: 19020, duration: 0 },
                { id: "eid499", tween: [ "style", "${_Rectangle3}", "border-width", '0px', { fromValue: '3px'}], position: 19520, duration: 0 },
                { id: "eid531", tween: [ "style", "${_Rectangle3}", "border-width", '3px', { fromValue: '0px'}], position: 22516, duration: 0 },
                { id: "eid532", tween: [ "style", "${_Rectangle3}", "border-width", '0px', { fromValue: '3px'}], position: 23016, duration: 0 },
                { id: "eid567", tween: [ "style", "${_Rectangle3}", "border-width", '3px', { fromValue: '0px'}], position: 25466, duration: 0 },
                { id: "eid568", tween: [ "style", "${_Rectangle3}", "border-width", '0px', { fromValue: '3px'}], position: 25966, duration: 0 },
                { id: "eid189", tween: [ "style", "${_Rectangle4}", "border-width", '0px', { fromValue: '0px'}], position: 0, duration: 0 },
                { id: "eid199", tween: [ "style", "${_Rectangle4}", "border-width", '3px', { fromValue: '0px'}], position: 1770, duration: 0 },
                { id: "eid204", tween: [ "style", "${_Rectangle4}", "border-width", '0px', { fromValue: '3px'}], position: 2270, duration: 0 },
                { id: "eid240", tween: [ "style", "${_Rectangle4}", "border-width", '3px', { fromValue: '0px'}], position: 5200, duration: 0 },
                { id: "eid241", tween: [ "style", "${_Rectangle4}", "border-width", '0px', { fromValue: '3px'}], position: 5700, duration: 0 },
                { id: "eid333", tween: [ "style", "${_Rectangle4}", "border-width", '3px', { fromValue: '0px'}], position: 7960, duration: 0 },
                { id: "eid334", tween: [ "style", "${_Rectangle4}", "border-width", '0px', { fromValue: '3px'}], position: 8460, duration: 0 },
                { id: "eid377", tween: [ "style", "${_Rectangle4}", "border-width", '3px', { fromValue: '0px'}], position: 10820, duration: 0 },
                { id: "eid378", tween: [ "style", "${_Rectangle4}", "border-width", '0px', { fromValue: '3px'}], position: 11320, duration: 0 },
                { id: "eid411", tween: [ "style", "${_Rectangle4}", "border-width", '3px', { fromValue: '0px'}], position: 13760, duration: 0 },
                { id: "eid412", tween: [ "style", "${_Rectangle4}", "border-width", '0px', { fromValue: '3px'}], position: 14260, duration: 0 },
                { id: "eid456", tween: [ "style", "${_Rectangle4}", "border-width", '3px', { fromValue: '0px'}], position: 16620, duration: 0 },
                { id: "eid457", tween: [ "style", "${_Rectangle4}", "border-width", '0px', { fromValue: '3px'}], position: 17120, duration: 0 },
                { id: "eid492", tween: [ "style", "${_Rectangle4}", "border-width", '3px', { fromValue: '0px'}], position: 20020, duration: 0 },
                { id: "eid493", tween: [ "style", "${_Rectangle4}", "border-width", '0px', { fromValue: '3px'}], position: 20520, duration: 0 },
                { id: "eid525", tween: [ "style", "${_Rectangle4}", "border-width", '3px', { fromValue: '0px'}], position: 23516, duration: 0 },
                { id: "eid526", tween: [ "style", "${_Rectangle4}", "border-width", '0px', { fromValue: '3px'}], position: 24016, duration: 0 },
                { id: "eid561", tween: [ "style", "${_Rectangle4}", "border-width", '3px', { fromValue: '0px'}], position: 26466, duration: 0 },
                { id: "eid562", tween: [ "style", "${_Rectangle4}", "border-width", '0px', { fromValue: '3px'}], position: 26966, duration: 0 },
                { id: "eid125", tween: [ "style", "${_segment1Copy3}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
                { id: "eid398", tween: [ "style", "${_segment1Copy3}", "display", 'block', { fromValue: 'none'}], position: 10320, duration: 0 },
                { id: "eid205", tween: [ "style", "${_Rectangle5}", "border-width", '0px', { fromValue: '0px'}], position: 0, duration: 0 },
                { id: "eid217", tween: [ "style", "${_Rectangle5}", "border-width", '3px', { fromValue: '0px'}], position: 2270, duration: 0 },
                { id: "eid222", tween: [ "style", "${_Rectangle5}", "border-width", '0px', { fromValue: '3px'}], position: 2770, duration: 0 },
                { id: "eid267", tween: [ "style", "${_Rectangle5}", "border-width", '3px', { fromValue: '0px'}], position: 5700, duration: 0 },
                { id: "eid268", tween: [ "style", "${_Rectangle5}", "border-width", '0px', { fromValue: '3px'}], position: 6200, duration: 0 },
                { id: "eid360", tween: [ "style", "${_Rectangle5}", "border-width", '3px', { fromValue: '0px'}], position: 8460, duration: 0 },
                { id: "eid361", tween: [ "style", "${_Rectangle5}", "border-width", '0px', { fromValue: '3px'}], position: 8960, duration: 0 },
                { id: "eid395", tween: [ "style", "${_Rectangle5}", "border-width", '3px', { fromValue: '0px'}], position: 11320, duration: 0 },
                { id: "eid396", tween: [ "style", "${_Rectangle5}", "border-width", '0px', { fromValue: '3px'}], position: 11820, duration: 0 },
                { id: "eid429", tween: [ "style", "${_Rectangle5}", "border-width", '3px', { fromValue: '0px'}], position: 14260, duration: 0 },
                { id: "eid430", tween: [ "style", "${_Rectangle5}", "border-width", '0px', { fromValue: '3px'}], position: 14760, duration: 0 },
                { id: "eid474", tween: [ "style", "${_Rectangle5}", "border-width", '3px', { fromValue: '0px'}], position: 17120, duration: 0 },
                { id: "eid475", tween: [ "style", "${_Rectangle5}", "border-width", '0px', { fromValue: '3px'}], position: 17620, duration: 0 },
                { id: "eid510", tween: [ "style", "${_Rectangle5}", "border-width", '3px', { fromValue: '0px'}], position: 20520, duration: 0 },
                { id: "eid511", tween: [ "style", "${_Rectangle5}", "border-width", '0px', { fromValue: '3px'}], position: 21020, duration: 0 },
                { id: "eid543", tween: [ "style", "${_Rectangle5}", "border-width", '3px', { fromValue: '0px'}], position: 24016, duration: 0 },
                { id: "eid544", tween: [ "style", "${_Rectangle5}", "border-width", '0px', { fromValue: '3px'}], position: 24516, duration: 0 },
                { id: "eid579", tween: [ "style", "${_Rectangle5}", "border-width", '3px', { fromValue: '0px'}], position: 26966, duration: 0 },
                { id: "eid580", tween: [ "style", "${_Rectangle5}", "border-width", '0px', { fromValue: '3px'}], position: 27466, duration: 0 }            ]
        }
    }
}
};


Edge.registerCompositionDefn(compId, symbols, fonts, resources, opts);

/**
 * Adobe Edge DOM Ready Event Handler
 */
$(window).ready(function() {
     Edge.launchComposition(compId);
});
})(jQuery, AdobeEdge, "EDGE-540608186");
